// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qahfxjceubhprjbozqos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhaGZ4amNldWJocHJqYm96cW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzA0MDksImV4cCI6MjA3MDY0NjQwOX0.YhaShgzpVjcE3a24Osbs2nmPSG-W2heAy0-_Y-RlFvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});